### PR TITLE
Add possibility to input key file data instead of location

### PR DESCRIPTION
**Pull request by Footmau**
Hello!
I need this possibility, because I use gokeepasslib through JNI and I'm passing keyfile data instead of location. In Android is really hard to obtain real path of file URI.

It could be helpful for other library users. Thanks.

### CODE REVIEW

**Comment by tobischo** [comment]
Please also add tests for newly added functionality

**Comment by Footmau** [comment]
Ok. Have you any doc how to run tests?

**Comment by tobischo** [comment]
`go test .` would do the trick

Go comes with all the bells and whistles. Testing is directly included.
You can also checkout the travis ci config in this repo to see how tests are executed

**Comment by Footmau** [comment]
Nice, really simple testing. I like Go :)
I updated changes.

**Comment by tobischo** [comment]
Thank you for the contribution

**Pull request merged**
