### PR TITLE
Set timestamp format version on file encoding

### PR DESCRIPTION
**Pull request by tobischo**

### CODE REVIEW

**Comment by tobischo** [comment]
@Footmau I haven't tested it yet, but just as a basis on what #59 could look like

**Comment by tobischo** [comment]
Added tests, so I am pretty confident that this should be working now

**Comment by Footmau** [comment]
> @Footmau I haven't tested it yet, but just as a basis on what #59 could look like

Thanks a lot. I'll review and test a little bit later.

**Comment by Footmau** [comment]
@tobischo seem it works well with my app.
Thanks a lot for this useful changes.

**Pull request merged**
