### PR TITLE
Document writing a file

### PR DESCRIPTION
**Pull request by joonas-fi**
Regarding: #19

### CODE REVIEW

**Comment by tobischo** [comment]
Very nice and working.
However: keepass 2 additionally encrypts passwords using salsa20 (or chacha20 in kdbx4 format).
Your passwords would be stored in cleartext in the database. The whole file is still encrypted though but while having the file opened for a longer time it would be easier possible to somehow get the password from a memory dump.
I suppose since the decrypt key is in memory as well that might be possible regardless, but to emulate the behaviour of keepass2 that should be added. Since I am not proficient enough in security related issues such as that, I'd suggest sticking to how it is done there.

**Comment by joonas-fi** [comment]
I was a bit lost on the "protected" keyword in the entries and what's the point of encrypting anything inside a file that's already encrypted..

If an attacker is able to read a RAM dump of the plaintext database after decryption, there is not much point in protecting the secrets in RAM if you're going to keep the decryption key in RAM anyway (which Keepass has to, to be able to read the passwords).

This all sounds like security by obscurity to me, which there is not much point in, more so with open source software as you can read the obfuscation implementation from the source code..

While it could theoretically help with attack methods blindly just scanning the RAM for strings that look like credentials, this kind of "secret protection in RAM" should not be done at the file format level but rather should instead be done in in-memory structures after loading the file - I think the developers are trying to combine in-memory structure and file format here and all it does is introduce unnecessary complexity.

Anyway, I do completely agree with you here that if this is what Keepass does, it is what we should imitate also. I'm not completely sure on how it should be implemented, so I need a bit of help here:

So should I add this:

```
func mkProtectedValue(key string, value string) gokeepasslib.ValueData {
	return gokeepasslib.ValueData{Key: key, Value: gokeepasslib.V{Content: value}, Protected: true}
}
```

And then change this:

```
entry.Values = append(entry.Values, mkValue("Password", "hunter2"))
```

Into this:

```
entry.Values = append(entry.Values, mkProtectedValue("Password", "hunter2"))
```

And then do:

```
salsaManager := NewSalsaManager(db.Headers.ProtectedStreamKey) // 32 bytes

// locks groups and entries recursively (encrypts values with Protected: true)
sm.LockGroup(rootGroup)
```

Obviously I now need to init the database before before calling LockGroup() because we need access to `ProtectedStreamKey`

It this implementation what you were referring to? :)

**Comment by tobischo** [comment]
Yes, that is what I am referring to.

Actually it is quite easy: the `ProtectedStreamKey` is already initialized in `gokeepasslib.NewFileHeaders()`.

Futhermore you can call `db.LockProtectedEntries()` to lock the entire database.

**Comment by tobischo** [comment]
I'll merge it and add the corresponding changes

**Comment by joonas-fi** [comment]
Sorry that I didn't manage to find the time to finalize the changes, and thanks for accepting the PR!

Might I suggest changing the repo description to "A library to read/write keepass 2 files written in go"? :)

**Comment by tobischo** [comment]
Don't mention it. I just had some time to spare so I took care of it.

**Pull request merged**
