### PR TITLE
#50 Extremely improved open AES database time.

### PR DESCRIPTION
**Pull request by Footmau**
Great optimization for users who have huge number of key encryption rounds in database settings.
Works two times faster than alternative implementations and maybe 40 times faster than previous implementation.

### CODE REVIEW

**Comment by tobischo** [comment]
Thank you for the contribution.

I take it part of the issue for the user with performance issues you mentioned was a huge rounds value?

Aside from that: if you make such a refactoring, it would be great if you could add 1 or 2 tests so that it is easier to evaluate that the result is still the same. Generally there should already have been tests before that though :grimacing:

**Comment by tobischo** [comment]
Release in v3.0.1

**Comment by Footmau** [comment]
Yes, this was root cause of the issue.
Of course i can add some tests and also improve performance a little bit more.

**Comment by tobischo** [comment]
What was the number of rounds configured in that case?

I added few tests just to have a degree of certainty that it still works 😄 
I also added a benchmark test to evaluate it better with explicit numbers

**Comment by Footmau** [comment]
It was about 20000, but it was a mobile device.
I tested with 100000000 on my PC and now it works 2 times faster than original KeePass.

**Pull request merged**
