### PR TITLE
Modular protected stream managers and external salsa20 implementation

### PR DESCRIPTION
**Pull request by ironmig**
Nice go-lang-ey improvement to protected stream manger (which is just an interface now which salsa20 satisfies), so in the future arc4 can be implemented without refactoring anything. Databases without protected streams are now supported via InsecureStreamManager. Modularity improvements for compression flags and stream id in headers.

### CODE REVIEW

**Comment by ironmig** [comment]
Just converted salsa20 to use implementation from golang.org/x/crypto/salsa20 (Golang's semiofficial packages). This should be easier to maintain and read, and ensures proper crypto implementation.

**Comment by tobischo** [comment]
Haven't looked through all of it yet, but please use gofmt

**Comment by ironmig** [comment]
Ran the changed files through gofmt

**Comment by tobischo** [comment]
Could you check whether tmp.kdbx from `TestDecodeFile` is still readable for you using Keepass2? I am having issues opening it: specifically I am getting 'One of the specified items was in an invalid format' (I am actually having that issue with the current master as well unfortunately :S )

**Comment by ironmig** [comment]
It seems to be something to do with the file attachment stuff that was added. My bad. I'll look into it.

**Comment by ironmig** [comment]
Can't really figure it out. The xml seems to be valid. I added a commit which just comments out the file attachment functionality for now. With it commented out, you can open tmp.kdbx with keepass2. I'll send you a pull request if I figure out what's wrong.

**Comment by tobischo** [comment]
ok, great! :)

**Comment by ironmig** [comment]
I found out what's wrong, but I'm not sure how to fix it. For whatever reason, keepass2 throws an error if the xml for a binaryreference doesn't have a self closing tag (e.g. <Value Ref="1" /> is okay, but <Value Ref="1"></Value> throws an error. I don't know enough about the xml package to get it to work. Perhaps you do.

**Comment by tobischo** [comment]
I'll take a look later :)

**Comment by tobischo** [comment]
Ok, right now I can see two solutions: a) custom marshaller for binary similar to boolWrapper or b) run a regex afterwards to replace
`<Value Ref="1"></Value>`
to
`<Value Ref="1" />`

I suppose a custom marshaller would be less likely to create weird behaviour

**Comment by ironmig** [comment]
Yeah, having BinaryReference satisfy Marshaller seems like the way to go. I started to look into it thinking you basically just write []byte, but it seems somewhat complicated to get it to not automatically add ending tag.

**Comment by tobischo** [comment]
You are right it is a bit more complicated - the suggestions I found also aimed at post processing.
That is what I did now as well - but at least I got it working that way...

**Comment by ironmig** [comment]
I filed a bug report for this at https://sourceforge.net/p/keepass/feature-requests/2023/ and have verified that it is fixed in the latest development snapshot of keepass2.

**Pull request merged**
