### PR TITLE
Minor optimization.

### PR DESCRIPTION
**Pull request by Footmau**

### CODE REVIEW

**Comment by tobischo** [comment]
Thank you for the contribution.

Since this is a package internal function and the masterKey is actually built in other package internal functions, I suppose it does not have unexpected side effects.
In general this optimization would also require a change for the function signature, since the masterKey that is passed in now holds the result value also.
From just looking at the function signature, that is not what I would expect.

In general in the go standard library, same as e.g. in `block.Encrypt` the function can be used in such a way to avoid additional allocation and it is up to the programmer who builds software around it to use it in such a way. In those cases the function makes it obvious through its API that the result will be stored in a parameter provided to the function.

Therefore I can see two options right now:
1. copy `masterKey` at the beginning of the function and then use the copied slice the same way you are using `masterKey` now. The current function signature would then match the behavour to say: ok, the returned slice is actually not the same one as the `masterKey`, which could be reused elsewhere.
2. change the function signature to make it more obvious that the given slice will be updated and it would be up to the user of the function to create a copy of the slice beforehand if possible

**Comment by Footmau** [comment]
Thanks for review.

I updated pull request according to approach 1.
But before 30ef432bc65c6e4f5717447f3001984ccacf37af the function also was modifying its key parameter.

**Comment by tobischo** [comment]
That's true. I wasn't very experienced with go when I first built this.
Since then it served its purpose for me so there was little need to make changes.
Now when changes are made anyway, there is the possibility to leave things in a better state than they used to be

**Comment by tobischo** [comment]
The way this repo was merged back into the branch for this pull request makes it really hard to actually merge this back into master.

`git rebase` also drops the `copy` part again, since it was added in a merge commit.
Can you maybe clean that up/create a clean history of the change which can be merged properly?

Otherwise I can also just apply the suggested changes in a new commit

**Comment by Footmau** [comment]
Sure, I will prepare new pull request.

**Comment by tobischo** [comment]
Closing since this was covered in #53

**Pull request closed without merging**
