### PR TITLE
Feature/handle bool defaults correctly

### PR DESCRIPTION
**Pull request by tobischo**
@Footmau Please take a look if this is working for you

Note that this would upgrade to v3.0.0 as it contains breaking changes

Addresses #45

### CODE REVIEW

**Comment by Footmau** [comment]
Hello, @tobischo, thanks for your fix.
But for me it doesn't works.
I didn't investigate deep, but bug is reproducing.

**Comment by Footmau** [comment]
I saved oroginal database in XML and found this:
`<EnableAutoType>null</EnableAutoType>`

**Comment by Footmau** [comment]
Probably, better solution will be initialize property only if value is "True"/"true" or "False"/'false', and do not initialize otherwise.

**Comment by tobischo** [comment]
It should be working now

**Comment by Footmau** [comment]
Yes, working for me now.
Thank you!

**Pull request merged**
